INSERT INTO exercises (name, muscle_group) VALUES
-- Chest
('Bench Press', 'Chest'),
('Incline Bench Press', 'Chest'),
('Decline Bench Press', 'Chest'),
('Close-Grip Bench Press', 'Chest'),
('Push-Up', 'Chest'),
('Incline Push-Up', 'Chest'),
('Decline Push-Up', 'Chest'),
('Dip', 'Chest'),
('Dumbbell Chest Press', 'Chest'),
('Incline Dumbbell Press', 'Chest'),
('Dumbbell Chest Fly', 'Chest'),
('Dumbbell Pullover', 'Chest'),
('Cable Chest Press', 'Chest'),
('Standing Cable Chest Fly', 'Chest'),
('Machine Chest Press', 'Chest'),
('Pec Deck', 'Chest'),
 
-- Shoulders
('Overhead Press', 'Shoulders'),
('Seated Dumbbell Shoulder Press', 'Shoulders'),
('Arnold Press', 'Shoulders'),
('Push Press', 'Shoulders'),
('Landmine Press', 'Shoulders'),
('Machine Shoulder Press', 'Shoulders'),
('Dumbbell Lateral Raise', 'Shoulders'),
('Cable Lateral Raise', 'Shoulders'),
('Machine Lateral Raise', 'Shoulders'),
('Dumbbell Front Raise', 'Shoulders'),
('Barbell Front Raise', 'Shoulders'),
('Dumbbell Rear Delt Row', 'Shoulders'),
('Reverse Dumbbell Flyes', 'Shoulders'),
('Face Pull', 'Shoulders'),
('Upright Row', 'Shoulders'),
('Handstand Push-Up', 'Shoulders'),
 
-- Arms 
('Barbell Curl', 'Arms'),
('Dumbbell Curl', 'Arms'),
('Hammer Curl', 'Arms'),
('Preacher Curl', 'Arms'),
('Incline Dumbbell Curl', 'Arms'),
('Concentration Curl', 'Arms'),
('Cable Curl', 'Arms'),
('EZ Bar Curl', 'Arms'),
('Spider Curl', 'Arms'),
('Tricep Pushdown With Rope', 'Arms'),
('Tricep Pushdown With Bar', 'Arms'),
('Overhead Cable Triceps Extension', 'Arms'),
('Dumbbell Lying Triceps Extension', 'Arms'),
('Dumbbell Standing Triceps Extension', 'Arms'),
('Skull Crushers', 'Arms'),
('Bench Dip', 'Arms'),
('Close-Grip Push-Up', 'Arms'),
('Farmers Walk', 'Arms'),
('Wrist Roller', 'Arms'),
('Barbell Wrist Curl', 'Arms'),
('Bar Hang', 'Arms'),
 
-- Back
('Deadlift', 'Back'),
('Sumo Deadlift', 'Back'),
('Rack Pull', 'Back'),
('Good Morning', 'Back'),
('Back Extension', 'Back'),
('Barbell Row', 'Back'),
('Pendlay Row', 'Back'),
('Dumbbell Row', 'Back'),
('Chest-Supported Dumbbell Row', 'Back'),
('T-Bar Row', 'Back'),
('Seated Cable Row', 'Back'),
('Inverted Row', 'Back'),
('Pull-Up', 'Back'),
('Chin-Up', 'Back'),
('Assisted Pull-Up', 'Back'),
('Lat Pulldown', 'Back'),
('Close-Grip Lat Pulldown', 'Back'),
('Straight Arm Lat Pulldown', 'Back'),
('Barbell Shrug', 'Back'),
('Dumbbell Shrug', 'Back'),
 
-- Legs
('Squat', 'Legs'),
('Front Squat', 'Legs'),
('Goblet Squat', 'Legs'),
('Box Squat', 'Legs'),
('Sumo Squat', 'Legs'),
('Pistol Squat', 'Legs'),
('Hack Squat', 'Legs'),
('Bulgarian Split Squat', 'Legs'),
('Leg Press', 'Legs'),
('Leg Extension', 'Legs'),
('Lying Leg Curl', 'Legs'),
('Seated Leg Curl', 'Legs'),
('Nordic Hamstring Curl', 'Legs'),
('Glute Ham Raise', 'Legs'),
('Romanian Deadlift', 'Legs'),
('Walking Lunge', 'Legs'),
('Reverse Lunge', 'Legs'),
('Step Up', 'Legs'),
('Box Jump', 'Legs'),
('Jump Squat', 'Legs'),
 
-- Glutes
('Hip Thrust', 'Glutes'),
('Glute Bridge', 'Glutes'),
('Single Leg Romanian Deadlift', 'Glutes'),
('Cable Glute Kickback', 'Glutes'),
('Cable Pull Through', 'Glutes'),
('Hip Abduction Machine', 'Glutes'),
('Donkey Kicks', 'Glutes'),
('Fire Hydrants', 'Glutes'),
('Clamshells', 'Glutes'),
('Frog Pumps', 'Glutes'),
 
-- Abs
('Plank', 'Abs'),
('Side Plank', 'Abs'),
('Weighted Plank', 'Abs'),
('Crunch', 'Abs'),
('Bicycle Crunch', 'Abs'),
('Cable Crunch', 'Abs'),
('Sit-Up', 'Abs'),
('Hanging Leg Raise', 'Abs'),
('Hanging Knee Raise', 'Abs'),
('Lying Leg Raise', 'Abs'),
('Core Twist', 'Abs'),
('Mountain Climbers', 'Abs'),
('Dead Bug', 'Abs'),
('Pallof Press', 'Abs'),
('Hollow Hold', 'Abs'),
('Ab Wheel Roll-Out', 'Abs'),
 
-- Calves
('Standing Calf Raise', 'Calves'),
('Seated Calf Raise', 'Calves'),
('Donkey Calf Raise', 'Calves'),
('Calf Raise in Leg Press', 'Calves');